---
trigger:
  branches:
    include:
    - master

variables:
  build: $(Build.BuildNumber)
  ubuntuImage: Ubuntu-18.04

stages:
  - stage: ImageBuildRelease
    displayName: Build and Release Container
    pool:
      vmImage: ${{ variables.ubuntuImage }}
    jobs:
      - job: ReleaseEximContainer
        displayName: Build and Release Container
        steps:
          - template: pipeline/acr_build.yml
            parameters:
              spACR: 'DTS-SS-PUBLIC-PROD'
              containerACRRepo: 'exim-relay'
              ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
                containerTag: "0.2.$(Rev:r)"
              ${{ if and(eq(variables['Build.Reason'], 'PullRequest'), ne(variables['Build.SourceBranchName'], 'master') ) }}:
                containerTag: "pr-$(System.PullRequest.PullRequestNumber)"
              ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), ne(variables['Build.SourceBranchName'], 'master') ) }}:
                containerTag: "pr-$(Build.BuildID)"